# Schema for the configuration files of google webfont loader api.

google_webfont_loader_api.settings:
  type: config_object
  label: 'Google Webfont Loader API settings'
  mapping:
    cache:
      type: integer
      label: 'Whether to use locally packaged webfont.js or CDN'
    display_style:
      type: string
      label: 'Whether the page should be displayed only after font has loaded'
    font:
      type: sequence
      label: 'Enabled fonts'
      sequence:
        type: any
    fontinfo_listing:
      type: sequence
      label: 'List of available fonts'
      sequence:
        type: any
